apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1 
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-test
        image: acalderon88/kube-training:1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "256M"
            cpu: "500m"

