apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata: app
      labels: app
        app: app
    spec:
      containers:
      - name: app
        image: 
        ports:
        - containerPort: 80
